version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build finished. Ready for deployment.

artifacts:
  files:
    - '**/*'
